frontend:
	sh components/frontend.sh
mongodb:
	sh components/mongodb.sh
catalogue:
	sh components/catalogue.sh
reddis:
	sh components/reddis.sh
user:
	sh components/user.sh
cart:
	sh components/cart.sh
mysql:
	sh components/mysql.sh
shipping:
	sh components/shipping.sh
rabbitmq:
	sh components/rabbitmq.sh
payment:
	sh components/payment.sh
