frontend:
	sh components/frontend.sh
mongodb:
	sh components/mongodb.sh
cart:
	sh components/cart.sh
catalogue:
	sh components/catalogue.sh
reddis:
	sh components/reddis.sh
user:
	sh components/user.sh